### PR TITLE
added settings & links to gtk documentation

### PR DESCRIPTION
**Pull request by Quantenzitrone**
- all added settings are tested and working
- links are to gtk4 documentation, since it is the newest

I will test and add more later, you can merge now or wait.

see #28

### CODE REVIEW

**Comment by derat** [comment]
Thanks! Would you mind keeping the settings sorted within the table? (I think the `Gtk/` ones might just need to be moved back to the beginning.)

**Comment by Quantenzitrone** [comment]
Oh, I thought moving the `Gtk/` down would be a good idea, since the `Net/` settings are more standardized, but sure.

**Comment by derat** [comment]
Thanks, I think I just have one comment.

**Comment by derat** [comment]
... which I really wish I could send you, but GitHub is being its usually uncooperative self and just shows it as stuck in a "Pending" state. In case it never actually sends it to you, here it is (in reference to `boolean` on L124):

> please keep this (and other types) as integer rather than boolean. this is referring to the underlying XSETTINGS type, and there's no boolean type, only integers: https://specifications.freedesktop.org/xsettings-spec/0.5/ar01s04.html

**Comment by Quantenzitrone** [comment]
ok that makes sense

**Comment by derat** [comment]
I've squashed and merged the PR. Thanks again!

**Pull request merged**
